Improve Telegram X template
ThemerBot/ThemerBot pull request #3
Opened 2019-06-12 14:11 UTC by Hkh12

Some of the issues related to TGX template are fixed. The important ones are written below:
- `headerTabActive` is visible
- shadows won't replace with separators
- Message selection color is more transparent now

Also, the bot can accept hexacodes with not only 6, but 3, 4 or 8 digits.

2019-06-12 22:46 UTC, YouTwitFace commented
> Also, the bot can accept hexacodes with not only 6, but 3, 4 or 8 digits.

1. The bot shouldn't support 8 digits
2. I would need to convert 3 to 6

To convert 3 to 6, you can do something like this:

```javascript
const colors = ctx.match[0]
    .split(``)
    .map(color => color.repeat(2))
    .join(``);
```

2019-06-13 02:40 UTC, vrumger requested changes

2019-06-13 02:40 UTC, vrumger commented on handlers/custom-color.js
> +    bot.hears(/^#(?:[\da-f]{2,3}){1,2}$/i, async ctx => {
This doesn't seem right
![image](https://user-images.githubusercontent.com/32808683/59390523-8b3d0980-8d3f-11e9-9b1c-6b520b78fe45.png)

2019-06-13 10:34 UTC, Hkh12 commented on handlers/custom-color.js
> +    bot.hears(/^#(?:[\da-f]{2,3}){1,2}$/i, async ctx => {
Yes, that was a fault. It should be:
```js
/^#(?:[\da-f]{3, 4}){1,2}$/i
```
And if you want to ignore the alpha:
```js
/^#(?:[\da-f]{3}){1,2}$/i
```

2019-06-13 11:31 UTC, vrumger requested changes
I think it would be better to check the hex code length before adding it to the colors array instead of checking for each template.

2019-06-13 22:39 UTC, vrumger approved these changes

2019-06-13 22:41 UTC, merged

2019-06-13 22:41 UTC, YouTwitFace commented
👍